import java.time.LocalDate;

public class AuditReportService {
    private ReportRepository repo;

    public AuditReportService(ReportRepository repo) {
        this.repo = repo;
    }

    public void generateFullAuditReport(UserSession s) {
        if (!s.getRank().equals("CPT") && !s.getRank().equals("LT")) {
            System.out.println("|  |    ACCESS DENIED: Officer rank required to view audit reports.");
            return;
        }

        System.out.println("|  |    ========== FULL AUDIT LOG REPORT ==========");
        System.out.println("|  |    Generated by: " + s.getRank() + " " + s.getUsername());
        System.out.println("|  |    Date: " + LocalDate.now());
        System.out.println("|  |");

        java.util.List<AuditLog> logs = repo.getAllAuditLogs();

        if (logs.isEmpty()) {
            System.out.println("|  |    No audit logs found.");
        } else {
            System.out.println("|  |    ID | User     | Action                                    | Time");
            System.out.println("|  |    ----|----------|-------------------------------------------|---------------------");
            for (AuditLog log : logs) {
                System.out.printf("|  |    %-3d | %-8s | %-41s | %s\n", log.id, log.user, log.action, log.time);
            }
        }

        System.out.println("|  |");
        System.out.println("|  |    ========== END OF REPORT ==========");
        repo.saveLog(s.getUsername(), "Generated full audit report");
    }

    public void generateReportByDateRange(UserSession s, String startDate, String endDate) {
        if (!s.getRank().equals("CPT") && !s.getRank().equals("LT")) {
            System.out.println("|  |    ACCESS DENIED: Officer rank required to view audit reports.");
            return;
        }

        System.out.println("|  |    ========== AUDIT REPORT BY DATE RANGE ==========");
        System.out.println("|  |    Date Range: " + startDate + " to " + endDate);
        System.out.println("|  |    Generated by: " + s.getRank() + " " + s.getUsername());
        System.out.println("|  |");

        java.util.List<AuditLog> logs = repo.getAuditLogsByDateRange(startDate, endDate);

        if (logs.isEmpty()) {
            System.out.println("|  |    No audit logs found in this date range.");
        } else {
            for (AuditLog log : logs) {
                System.out.println("|  |    [" + log.time + "] " + log.user + ": " + log.action);
            }
        }
