public class OfficerService {
    private ReportRepository repo;

    public OfficerService(ReportRepository repo) {
        this.repo = repo;
    }

    public void generateSitRep(UserSession s) {
        if (!s.getRank().equals("CPT") && !s.getRank().equals("LT")) {
            System.out.println("|  |    ACCESS DENIED: Officer rank required for SitRep.");
            return;
        }

        System.out.println("|  |    === COMMANDER SITREP GENERATED ===");
        System.out.println("|  |    Status: Outpost Secure | Personnel: 100%");
        System.out.println("|  |    Report generated by: " + s.getRank() + " " + s.getUsername());
        repo.saveLog(s.getUsername(), "Generated SitRep");
    }
}
